name: npm-publish
on:
  push:
    branches:
      - main

jobs:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: 'Automated Version Bump'
          uses: 'phips28/gh-action-bump-version@master'
          with:
            tag-prefix:  ''
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 
